### ISSUE TITLE
how to run create_gt_test_set_shtech.m in matlab/octave

### ISSUE THREAD

**Issue by haiyang-traceto** [priyanka-kasture/Crowd-Counting-with-MCNNs#2]

**Comment by haiyang-traceto** [comment]
I had checked the readme file, but have no idea about how to run the create_gt_test_set_shtech.m file.

**Comment by sohaiblaraba** [comment]
I think it's the same as the folder available in many gits. Like this one: https://github.com/svishwa/crowdcount-cascaded-mtl/tree/master/data_preparation
I have tested it and it works.
You just need to 
- change the names of the folders **part_A** and **part_B** to **part_A_final** and **part_B_final** respectively. 
- change the name of the folder **ground-truth** to **ground_truth**
- and, if you are using Octave (I don't know about Matlab), run **pkg load image** before runing the code (to import necessary lib).

(again, if you are using Octave, there's a missing function called **rng** in **create_training_set_shtech.m**, you can add these lines (creating the function) at the beginning:

```
function rng(x) 
  randn("seed",x) 
  rand("seed",x) 
end
```

**Comment by chajnoven** [comment]
Hello, I have this problem:
Image Loading!
Traceback (most recent call last):
  File "test.py", line 26, in <module>
    mcnn.predict()
  File "C:\Users\Administrator\Crowd-Counting-with-MCNNs\network.py", line 286, in predict
    img = (img - 127.5) / 128
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

an array type can't be broadcast? I don't know what it is mean.
