### ISSUE TITLE
type error!

### ISSUE THREAD

**Issue by chajnoven** [priyanka-kasture/Crowd-Counting-with-MCNNs#3]
Hello, I have this problem:
Image Loading!
Traceback (most recent call last):
File "test.py", line 26, in 
mcnn.predict()
File "C:\Users\Administrator\Crowd-Counting-with-MCNNs\network.py", line 286, in predict
img = (img - 127.5) / 128
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

an array type can't be broadcast? I don't know what it is mean.

**Comment by lichenxiii** [comment]
> Hello, I have this problem:
> Image Loading!
> Traceback (most recent call last):
> File "test.py", line 26, in
> mcnn.predict()
> File "C:\Users\Administrator\Crowd-Counting-with-MCNNs\network.py", line 286, in predict
> img = (img - 127.5) / 128
> TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
> 
> an array type can't be broadcast? I don't know what it is mean.

hello do you solve this ques, I meet this ques too
